language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.6.1 DJANGO_SETTINGS_MODULE="poppurri.settings.test"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install -r requirements/test.txt
script:
  - python poppurri/manage.py test
