language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.6.1 DJANGO_SETTINGS_MODULE="poppurri.settings.test"
install:
  - pip install -r requirements/test.txt
script:
  - cd poppurri; python manage.py test
